### ISSUE TITLE
Application server issues 

### ISSUE THREAD

**Issue by yehessa** [xisiot/lora-application-server#11]
Hello
Can someone help me with the application server. It does not work.

Best

**Comment by houluy** [comment]
Hi, this repo is no longer maintaining. Please use ChirpStack which is a better implementation of LoRaWAN. Thanks!

**Comment by yehessa** [comment]
Hello
In fact it is the web server. The application, the joint server and the server works perfectly.
Can you provide any screen from the web server.
I will try to design.
